name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag nhatkytran/docker-react

    - name: Run tests
      run: docker run -e CI=true nhatkytran/docker-react npm run test
